package enums;

public enum CardGroup {
    ALL,
    ENEMY,
    FRIENDS,
    FRIENDS_DECK_HAND,
    FRIENDS_ONLY_DECK,
    FRIENDS_ONLY_HAND,
    ENEMY_MINIONS,
    FRIEND_MINIONS,
    FRIEND_MINIONS_EXCEPT_SELF,
    FRIEND_MINIONS_DAMAGED,
    ALL_MINIONS,
    ALL_MINIONS_EXCEPT_SELF,
    ALL_MINIONS_UNDAMAGED,
    FRIEND_HERO,
    ENEMY_HERO,
    SELF,
    DEAD_MINIONS,

    TYPE_CARD
}
