package enums;

public enum SelectingCardMethod {
    ONE_RANDOM,
    PLAYER_SELECTS,
    DETERMINED_GROUP,
    DETERMINED_CARD,
    DETERMINED_LATER,
    LAST_DRAWN_CARD,
    RECENTLY_PLAYED_CARD,
    RECENTLY_SUMMONED_CARD,
    RECENTLY_RECEIVED_CARD,
    RECENTLY_TRANSFORMED_CARD,
}
