package network.api;

public enum MessageType {
    // Source: Server
    PLAYER_UPDATE,
    SHOW_MESSAGE,
    SHOW_GO_SHOP_OPTION,
    GO_TO_LOGIN_PANEL,
    SUCCESSFUL_LOGIN,
    PLAY_ACCESS,
    AUTH_TOKEN,
    UPDATE_GAME_PANEL,
    RANKS_TABLE_UPDATE,

    UPDATE_COUNTER,
    UPDATE_CHATS,

    CHOOSE_PASSIVE,
    CHOOSE_CARD,
    CHOOSE_CARDS,

    // Source: Player
    PLAYER_UPDATE_REQUEST,
    RANKS_UPDATE_REQUEST,
    BUY_CARD,
    SELL_CARD,
    SIGN_IN,
    SIGN_UP,
    SIGN_OUT,
    DELETE_PLAYER,
    REMOVE_DECK,
    REMOVE_CARD_FROM_DECK,
    ADD_CARD_TO_DECK,
    CREATE_DECK,
    ACTIVATE_DECK,
    CHANGE_DECK_DETAILS,

    CREATE_LOCAL_GAME,
    CREATE_FILE_GAME,
    CREATE_MULTIPLAYER_GAME,
    CREATE_VS_AI_GAME,

    GAME_ACTION_END_TURN,
    GAME_ACTION_LEAVE_MATCH,
    GAME_ACTION_ENTRY,

    PASSIVE_CHOSE,
    CARD_CHOSE,
    CARDS_CHOSE,

    CHAT_MESSAGE,

}
